(define (connect-return-to-load urlbar view)
  (c-define (load-slot) () void "load_slot" ""
    (let ((text (q-line-edit-text)))
      (if (< (q-string-index-of (q-string-new "://") 0))
          (q-web-view-load (q-url-new (q-string-prepend text "http://")))
          (q-web-view-load (q-url-new text)))))
  (let ((proxy (slot-proxy-new load-slot)))
    (q-connect urlbar "returnPressed" proxy "work")))

(let ((app (q-application-new (length (command-line)) (command-line)))
      (window (q-main-window-new))
      (toolbar (q-tool-bar-new))
      (urlbar (q-line-edit-new))
      (view (q-web-view-new)))
  (connect-return-to-load urlbar view)
  (q-tool-bar-add-widget toolbar urlbar)
  (q-main-window-add-tool-bar window toolbar)
  (q-main-window-set-central-widget window view)
  (q-main-window-show window)
  (q-application-exec app))